"""add docker mirror config

Revision ID: 15101898fbeb
Revises: 21f8b3f1379a
Create Date: 2026-06-04 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15101898fbeb'
down_revision: Union[str, None] = '21f8b3f1379a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docker_mirror_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_api_url', sa.String(length=500), nullable=True),
    sa.Column('registry_mirror', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('docker_mirror_configs')
    # ### end Alembic commands ###
