"""refactor orchestration to composition template

Revision ID: 19f559b2c13d
Revises: 16c37fce85d1
Create Date: 2026-06-27 20:25:47.326395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19f559b2c13d'
down_revision: Union[str, None] = '16c37fce85d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_orchestration_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orchestration_id', sa.Integer(), nullable=False),
    sa.Column('instance_name', sa.String(length=100), nullable=False),
    sa.Column('shared_config', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['app_orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('app_instances', sa.Column('orchestration_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'app_instances', 'app_orchestration_instances', ['orchestration_group_id'], ['id'])
    op.add_column('app_orchestrations', sa.Column('app_composition', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False))
    op.add_column('app_orchestrations', sa.Column('shared_config_schema', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False))
    op.drop_column('app_orchestrations', 'type')
    op.drop_column('app_orchestrations', 'backup_paths')
    op.drop_column('app_orchestrations', 'readme')
    op.drop_column('app_orchestrations', 'source_dir')
    op.drop_column('app_orchestrations', 'yaml_template')
    op.drop_column('app_orchestrations', 'changelog')
    op.drop_column('app_orchestrations', 'suggested_plugins')
    op.drop_column('app_orchestrations', 'config_schema')
    op.drop_column('app_orchestrations', 'architectures')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_orchestrations', sa.Column('architectures', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.add_column('app_orchestrations', sa.Column('config_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('app_orchestrations', sa.Column('suggested_plugins', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('app_orchestrations', sa.Column('changelog', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('app_orchestrations', sa.Column('yaml_template', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('app_orchestrations', sa.Column('source_dir', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('app_orchestrations', sa.Column('readme', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('app_orchestrations', sa.Column('backup_paths', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.add_column('app_orchestrations', sa.Column('type', sa.VARCHAR(length=20), server_default=sa.text("'compose'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('app_orchestrations', 'shared_config_schema')
    op.drop_column('app_orchestrations', 'app_composition')
    op.drop_constraint(None, 'app_instances', type_='foreignkey')
    op.drop_column('app_instances', 'orchestration_group_id')
    op.drop_table('app_orchestration_instances')
    # ### end Alembic commands ###
