"""drop apps source_dir column

Revision ID: 69f13f841e93
Revises: 19f559b2c13d
Create Date: 2026-06-30 10:36:13.632698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f13f841e93'
down_revision: Union[str, None] = '19f559b2c13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'source_dir')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('source_dir', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
