"""enhance app template models

Revision ID: 6d0cdf7a7696
Revises: 042b6115be2a
Create Date: 2026-06-17 16:33:59.153851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0cdf7a7696'
down_revision: Union[str, None] = '042b6115be2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('app_instance_backups'):
        op.create_table('app_instance_backups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('instance_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('path', sa.String(length=500), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('backup_type', sa.String(length=20), nullable=False),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['instance_id'], ['app_instances.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    existing_instance_cols = {c['name'] for c in inspector.get_columns('app_instances')}
    if 'template_version' not in existing_instance_cols:
        op.add_column('app_instances', sa.Column('template_version', sa.String(length=20), server_default='1.0.0', nullable=False))
    if 'status' not in existing_instance_cols:
        op.add_column('app_instances', sa.Column('status', sa.String(length=20), server_default='running', nullable=False))
    if 'backup_config' not in existing_instance_cols:
        op.add_column('app_instances', sa.Column('backup_config', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    if 'last_backup_at' not in existing_instance_cols:
        op.add_column('app_instances', sa.Column('last_backup_at', sa.DateTime(), nullable=True))

    existing_template_cols = {c['name'] for c in inspector.get_columns('app_templates')}
    if 'type' not in existing_template_cols:
        op.add_column('app_templates', sa.Column('type', sa.String(length=20), server_default='compose', nullable=False))
    if 'changelog' not in existing_template_cols:
        op.add_column('app_templates', sa.Column('changelog', sa.Text(), nullable=True))
    if 'backup_paths' not in existing_template_cols:
        op.add_column('app_templates', sa.Column('backup_paths', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    if 'source_dir' not in existing_template_cols:
        op.add_column('app_templates', sa.Column('source_dir', sa.String(length=500), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_templates', 'source_dir')
    op.drop_column('app_templates', 'backup_paths')
    op.drop_column('app_templates', 'changelog')
    op.drop_column('app_templates', 'type')
    op.drop_column('app_instances', 'last_backup_at')
    op.drop_column('app_instances', 'backup_config')
    op.drop_column('app_instances', 'status')
    op.drop_column('app_instances', 'template_version')
    op.drop_table('app_instance_backups')
    # ### end Alembic commands ###
