"""add_app_configs_to_orchestration_instance

Revision ID: ccfe1536e1fa
Revises: 69f13f841e93
Create Date: 2026-06-30 16:50:58.240096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfe1536e1fa'
down_revision: Union[str, None] = '69f13f841e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'app_orchestration_instances',
        sa.Column('app_configs', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_orchestration_instances', 'app_configs')
    # ### end Alembic commands ###
