"""add_app_id_to_app_instances

Revision ID: ede98ce2cc6c
Revises: 4164c6122006
Create Date: 2026-06-18 21:57:40.555837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede98ce2cc6c'
down_revision: Union[str, None] = '4164c6122006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_id', sa.Integer(), nullable=True))
        batch_op.alter_column('template_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.create_foreign_key('fk_app_instances_app_id', 'apps', ['app_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_instances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_app_instances_app_id', type_='foreignkey')
        batch_op.alter_column('template_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.drop_column('app_id')
    # ### end Alembic commands ###
